/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.project;

import java.util.ArrayList;
import java.util.LinkedList;

public class App {
  public String getGreeting() {
    return "Hello world.2223333";
  }

  public static void main(String[] args) {

    String s1 = new String("aaa");
    String s2 = new String("ddd");


    LinkedList list = new LinkedList();
    ArrayList list2 = new ArrayList();
    list.add(s1);
    list2.add(s1);
    list2.add(s1);
    list2.add(s2);
    list.add(s1);
    list.add(s2);
    list.add(s1);
    list.add(s1);
    list.add(s1);

    System.out.println(list.get(0));
    System.out.println(list.get(1));
    System.out.println(list.get(2));

    System.out.println(list.size());
    System.out.println("되나여?2222222");


  }
}
