/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.project;

public class App {
  public String getGreeting() {
    return "Hello world.2223333";
  }

  public static void main(String[] args) {

    System.out.println("되나여?");


  }
}
