/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.project;

public class App {
  public String getGreeting() {
    return "Hello world.2223333";
  }

  public static void main(String[] args) {

    System.out.println("ㅁ2");
    System.out.println("지웠습니당");
    System.out.println("저장합니다.2!");
    System.out.println("저장합니다.!");
    System.out.println("저장합니다.!");

    System.out.println("ㅁ");
    int a = 100;
    if (a > 50) {
      System.out.println("아 크구나...");
    }
    System.out.println("오호라... 점심 먹을 때가 되었네...헐...");
    System.out.println("푸시푸시");

  }
}
